
server:
  port: 8061
  replica-port: 8062
spring:
  application:
    name: com.spring.cloud.eureka.demo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${server.replica-port}/eureka/
