
server:
  port: 8763
spring:
  application:
    name: api.springcloud.com # 必须是预先定义的"域名", 不然消费端找不到服务

eureka:
  client:
    eureka-server-connect-timeout-seconds: 1
    eureka-server-read-timeout-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
